# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/bootstrap/grafana/dev/proxmox/base/dashboard/terraform.tfstate"
  }
}
