# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/bootstrap/git/shared/github/global/repository/terraform.tfstate"
  }
}
