# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/main-cluster/argo-cd/dev/proxmox/vault/auth/terraform.tfstate"
  }
}
