# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/main-cluster/vault/dev/proxmox/base/kubernetes-auth/terraform.tfstate"
  }
}
