# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/main-cluster/cilium/dev/proxmox/main-cluster/helm/terraform.tfstate"
  }
}
