# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/bootstrap/vault/shared/proxmox/base/pki/terraform.tfstate"
  }
}
