# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/workspace/personal/infrastructure/terraform/lab/main-cluster/cert-manager/dev/proxmox/main-cluster/vault-aws-keys/terraform.tfstate"
  }
}
